#VAMOS A CREAR UN DICCIONARIO QUE CONTENGA INFORMACION PERSONAL
#CON EL NOMBRE CIUDAD EDAD PROFESION TELEFONO
#INIZIALIZAMOS NUESTRA VARIABLE i EN CERO
i=0
#UTILIZAMOS EL BUCLE WHILE PARA REPETIR EL BLOQUE DE CODIGO
#MIENTRAS LA CONDICION SEA VERDADERA
while True:
    #COLOCAMOS LAS VARIABLES Y PEDIMOS LOS DATOS AL USUARIO
    NOMBRE1 = input("INGRESE SU NOMBRE:")
    EDAD = input("INGRESE SU EDAD:")
    CIUDAD = input("INGRESE LA CIUDAD DE RESIENCIA:")
    PROFESION = input("INGRESE SU PROFESION:")
    TELEFONO = input("INGRESE SU NUMERO TELEFONICO:")
    #CREAMOS NUESTRO DICCIONARIO DE INFORMACION PERSONAL CON LAS PALABRAS CLAVE
    informacion_personal = [{"NOMBRE": NOMBRE1, "EDAD": EDAD, "CIUDAD": CIUDAD,
               "PROFESION": PROFESION, "TELEFONO": TELEFONO}

              ]
    #PREGUNTAMOS AL USUARIO SI QUIERE SEGIUR AGREGANDO INFORMACION
    respuesta=input("¿DESEA CONTINUAR AGREGANDO MAS INFORMACION SI O NO? ")
    #USAMOS EL CONDICIONAL IF
    #SI LA RESPUESTA ES DIFERENTE DE si el programa terminara
    #caso contrario seguira almacenando mas infromacion
    if respuesta!="si":
        break
print("INFORMACION PERSONAL")
#USAMOS EL BUCLE FOR PARA IMPRIMIR EL DICCIONARIO RESULTANTE
for i in range(len(informacion_personal)):

    print(informacion_personal[0]["NOMBRE"])
    print(informacion_personal[0]["EDAD"])
    print(informacion_personal[0]["CIUDAD"])
    print(informacion_personal[0]["PROFESION"])
    print(informacion_personal[0]["TELEFONO"])